### ISSUE TITLE
AttributeError: 'RunModelResult' object has no attribute 'errored'

### ISSUE THREAD

**Issue by michael-erasmus** [bufferapp/budbt#2]
Hi @davidgasquez!

I ran into this error today when trying to deploy the new Helpscout models in `buffer-dbt`

I first saw the error on production and then also managed to replicate it locally by doing:

```
make dev
budbt run -m helpscout
```

The models seem to have built fine without failing.

Initially, I thought something might be up with the Helpscout models but I seem to be getting the same error with running the base models

```
budbt run -m base
```

Here is the full trace of the error:

```
Traceback (most recent call last):
  File "/usr/local/bin/budbt", line 11, in <module>
    load_entry_point('budbt', 'console_scripts', 'budbt')()
  File "/tmp/budbt/cli.py", line 45, in main
    if res.errored:
  File "/usr/local/lib/python3.6/site-packages/dbt/api/object.py", line 125, in __getattr__
    ).format(type(self).__name__, name))
AttributeError: 'RunModelResult' object has no attribute 'errored'
```

It seems to be happening on this line: https://github.com/bufferapp/budbt/blob/master/cli.py#L38

**Comment by davidgasquez** [comment]
Nice catch @michael-erasmus! This seems to be related to us moving to `0.13.0`. [I've sent a small patch and should be working again once the image is rebuilt](https://github.com/bufferapp/budbt/commit/3fb13eb62ad03ed438a0899b12cad34d46425f06).

That said, I don't think this workflow is ideal as `dbt` is quickly evolving, and we'll need to stay on top of what changes they add. Using something like `dbt cloud` could remove this step, but we'll be also some control over the logs.

**Comment by michael-erasmus** [comment]
Thanks for the fix @davidgasquez!

> I don't think this workflow is ideal as dbt is quickly evolving, and we'll need to stay on top of what changes they add. Using something like dbt cloud could remove this step, but we'll be also some control over the logs.

Yeah, I think you're right. Definitely feels brittle to be relying on an unsanctioned API here. Let's keep thinking about that and we'll look into dbt cloud when we get a chance.
